joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

egm_state_controller:
  type         : abb_egm_state_controller/EGMStateController
  publish_rate : 250

left_arm_vel_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - yumi_robl_joint_1
    - yumi_robl_joint_2
    - yumi_robl_joint_3
    - yumi_robl_joint_4
    - yumi_robl_joint_5
    - yumi_robl_joint_6
    - yumi_robl_joint_7
  gains:
    yumi_robl_joint_1: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_2: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_3: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_4: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_5: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_6: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_7: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
  constraints:
    stopped_velocity_tolerance: 0
    goal_time: 1
  velocity_ff:
    yumi_robl_joint_1: 1.0
    yumi_robl_joint_2: 1.0
    yumi_robl_joint_3: 1.0
    yumi_robl_joint_4: 1.0
    yumi_robl_joint_5: 1.0
    yumi_robl_joint_6: 1.0
    yumi_robl_joint_7: 1.0
  stop_trajectory_duration: 0
right_arm_vel_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - yumi_robr_joint_1
    - yumi_robr_joint_2
    - yumi_robr_joint_3
    - yumi_robr_joint_4
    - yumi_robr_joint_5
    - yumi_robr_joint_6
    - yumi_robr_joint_7
  gains:
    yumi_robr_joint_1: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_2: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_3: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_4: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_5: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_6: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_7: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
  constraints:
    stopped_velocity_tolerance: 0
    goal_time: 1
  velocity_ff:
    yumi_robr_joint_1: 1.0
    yumi_robr_joint_2: 1.0
    yumi_robr_joint_3: 1.0
    yumi_robr_joint_4: 1.0
    yumi_robr_joint_5: 1.0
    yumi_robr_joint_6: 1.0
    yumi_robr_joint_7: 1.0
  stop_trajectory_duration: 0
both_arms_vel_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - yumi_robl_joint_1
    - yumi_robl_joint_2
    - yumi_robl_joint_3
    - yumi_robl_joint_4
    - yumi_robl_joint_5
    - yumi_robl_joint_6
    - yumi_robl_joint_7
    - yumi_robr_joint_1
    - yumi_robr_joint_2
    - yumi_robr_joint_3
    - yumi_robr_joint_4
    - yumi_robr_joint_5
    - yumi_robr_joint_6
    - yumi_robr_joint_7
  gains:
    yumi_robl_joint_1: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_2: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_3: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_4: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_5: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_6: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robl_joint_7: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_1: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_2: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_3: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_4: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_5: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_6: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
    yumi_robr_joint_7: {p: 10.0, i: 0.5, d: 1, i_clamp: 0.1}
  constraints:
    stopped_velocity_tolerance: 0
    goal_time: 1
  velocity_ff:
    yumi_robl_joint_1: 1.0
    yumi_robl_joint_2: 1.0
    yumi_robl_joint_3: 1.0
    yumi_robl_joint_4: 1.0
    yumi_robl_joint_5: 1.0
    yumi_robl_joint_6: 1.0
    yumi_robl_joint_7: 1.0
    yumi_robr_joint_1: 1.0
    yumi_robr_joint_2: 1.0
    yumi_robr_joint_3: 1.0
    yumi_robr_joint_4: 1.0
    yumi_robr_joint_5: 1.0
    yumi_robr_joint_6: 1.0
    yumi_robr_joint_7: 1.0
  stop_trajectory_duration: 0

# left_arm_pos_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - yumi_robl_joint_1
#     - yumi_robl_joint_2
#     - yumi_robl_joint_3
#     - yumi_robl_joint_4
#     - yumi_robl_joint_5
#     - yumi_robl_joint_6
#     - yumi_robl_joint_7

# right_arm_pos_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - yumi_robr_joint_1
#     - yumi_robr_joint_2
#     - yumi_robr_joint_3
#     - yumi_robr_joint_4
#     - yumi_robr_joint_5
#     - yumi_robr_joint_6
#     - yumi_robr_joint_7

# both_arms_pos_controller:
#   type: position_controllers/JointTrajectoryController
#   joints: [yumi_robl_joint_1, yumi_robl_joint_2, yumi_robl_joint_3, yumi_robl_joint_4, yumi_robl_joint_5, yumi_robl_joint_6, yumi_robl_joint_7, 
#   yumi_robr_joint_1, yumi_robr_joint_2, yumi_robr_joint_3, yumi_robr_joint_4, yumi_robr_joint_5, yumi_robr_joint_6, yumi_robr_joint_7]

# A controller to forward joint trajectories to the robot
# forward_joint_trajectories:
#     type: "pass_through_controllers/JointTrajectoryController" # CartesianTrajectoryController
#     joints:
#     - joint1
#     - joint2
#     - joint3
#     - joint4
#     - joint5
#     - joint6

# A controller to forward joint trajectories to the robot
# left_arm_controller:
#     type: "pass_through_controllers/JointTrajectoryController"
#     joints:
#       - yumi_robl_joint_1
#       - yumi_robl_joint_2
#       - yumi_robl_joint_3
#       - yumi_robl_joint_4
#       - yumi_robl_joint_5
#       - yumi_robl_joint_6
#       - yumi_robl_joint_7
# right_arm_controller:
#     type: "pass_through_controllers/JointTrajectoryController"
#     joints:
#     - yumi_robr_joint_1
#     - yumi_robr_joint_2
#     - yumi_robr_joint_3
#     - yumi_robr_joint_4
#     - yumi_robr_joint_5
#     - yumi_robr_joint_6
#     - yumi_robr_joint_7
# both_arms_controller:
#     type: "pass_through_controllers/JointTrajectoryController"
#     joints:
#     - yumi_robr_joint_1
#     - yumi_robr_joint_2
#     - yumi_robr_joint_3
#     - yumi_robr_joint_4
#     - yumi_robr_joint_5
#     - yumi_robr_joint_6
#     - yumi_robr_joint_7    